# Generated by Django 4.1 on 2022-08-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitman', '0002_alter_hitmen_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitmen',
            name='password',
            field=models.CharField(default=123456, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hitmen',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
