# Generated by Django 4.1 on 2022-08-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitman', '0003_hitmen_password_alter_hitmen_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitmen',
            name='is_boss',
            field=models.BooleanField(default=False),
        ),
    ]
