# Generated by Django 4.1 on 2022-08-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitman', '0004_hitmen_is_boss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hitmen',
            old_name='is_boss',
            new_name='isBoss',
        ),
    ]
