# Generated by Django 4.1 on 2022-08-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitman', '0005_rename_is_boss_hitmen_isboss'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitmen',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
