# Generated by Django 4.1 on 2022-08-09 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hitman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.IntegerField()),
                ('desc', models.TextField()),
                ('target', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('Failed', 'Failed'), ('Completed', 'Completed')], max_length=9)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitman.hitmen')),
            ],
            options={
                'verbose_name': 'Hits',
            },
        ),
    ]
